### ISSUE TITLE
Determining model delta fails due to null values in correlation keys

### ISSUE THREAD

**Issue by ohecker** [devonfw/solicitor#57]
Null values in the data of artifacts (e.g. an undefined "groupId") might result in null values of the calculated correlation keys. This makes the delta calculation fail with the following exception:
```
2020-05-09 08:42:36.133 ERROR 16012 --- [main] c.d.t.solicitor.SolicitorApplication     : [SOLI-003] Solicitor processing aborted

java.lang.NullPointerException: null
	at com.devonfw.tools.solicitor.writer.data.DataTableDifferImpl.searchAndRemoveFromOldTableRowSet(DataTableDifferImpl.java:266) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.writer.data.DataTableDifferImpl.assignCorrelatedRows(DataTableDifferImpl.java:115) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.writer.data.DataTableDifferImpl.correlateTable(DataTableDifferImpl.java:154) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.writer.data.DataTableDifferImpl.diff(DataTableDifferImpl.java:185) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.writer.WriterFacadeImpl.getDataTables(WriterFacadeImpl.java:81) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.writer.WriterFacadeImpl.writeResult(WriterFacadeImpl.java:97) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.Solicitor.mainProcessing(Solicitor.java:114) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.Solicitor.run(Solicitor.java:162) ~[classes!/:1.0.2]
	at com.devonfw.tools.solicitor.SolicitorApplication.main(SolicitorApplication.java:42) ~[classes!/:1.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [solicitor.jar:1.0.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [solicitor.jar:1.0.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [solicitor.jar:1.0.2]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593) [solicitor.jar:1.0.2]
```

**Comment by ohecker** [comment]
Closed in release 1.0.3
