### ISSUE TITLE
GradleReader and GradleReader2 fail if input file contains empty list

### ISSUE THREAD

**Issue by ohecker** [devonfw/solicitor#87]
If the input file to processed by `GradleReader` or `GradleReader2` contains only an empty list ( [] ) the Reader fails and Solicitor terminates:

```
Exception:
java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
        at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509) ~[na:na]
        at java.base/java.util.ArrayList.subList(ArrayList.java:1138) ~[na:na]
        at com.devonfw.tools.solicitor.reader.gradle.GradleReader2.readInventory(GradleReader2.java:62) ~[classes!/:1.2.0]
        at com.devonfw.tools.solicitor.Solicitor.readInventory(Solicitor.java:140) ~[classes!/:1.2.0]
        at com.devonfw.tools.solicitor.Solicitor.mainProcessing(Solicitor.java:116) ~[classes!/:1.2.0]
        at com.devonfw.tools.solicitor.Solicitor.run(Solicitor.java:199) ~[classes!/:1.2.0]
        at com.devonfw.tools.solicitor.SolicitorApplication.main(SolicitorApplication.java:42) ~[classes!/:1.2.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[solicitor.jar:1.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[solicitor.jar:1.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[solicitor.jar:1.2.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593) ~[solicitor.jar:1.2.0]
```

Solicitor should not terminate in this case but continue processing - possibly writing a WARN message.

This affects Solicitor version 1.2.0 and earlier.

**Comment by ohecker** [comment]
Fixed with commit https://github.com/devonfw/solicitor/commit/8510af6f124996df873f6e5ac179472b0675b401 (v.1.2.3)
